### ISSUE TITLE
MordhauWearable

### ISSUE THREAD

**Issue by SoomRK** [Net-Slayer/Mordhau_uSDK#10]
MordhauWearables are missing the option where you used to be able to select what coifs, arms, shoulders, etc could be attached to the main 3 " Head, Upperchest, and Leg" 
it is replaced with a single "byte" that appears to do nothing.

**Comment by Net-Slayer** [comment]
please can you provide further information on this error?
Once this one is fixed, 1.3.1 will be ready

**Comment by Net-Slayer** [comment]
Fixed for 1.3.1
