### ISSUE TITLE
Mordhau Visual Error

### ISSUE THREAD

**Issue by ModRhaegar** [Net-Slayer/Mordhau_uSDK#11]
![image](https://user-images.githubusercontent.com/90299996/132443381-6a66bd75-10c8-444f-8ec9-21e15314a210.png)
This is the error I'm getting in Visual right now and wondering what I need to do to go about fixing this error. 
Also I'm not fluent in reading or writing code.

I thought it could possibly be because I didn't have it switched over to 4.25 correctly after getting this error when trying to switch to 4.25
![image](https://user-images.githubusercontent.com/90299996/132443696-e4946d9d-c89b-439c-9d9a-2cfd0933b353.png)

**Comment by Net-Slayer** [comment]
You can usually solve this error by right clicking your Mordhau.uproject > Generate project files.
You may have to update your .net framework SDKs to the version it may display in the error
usually it's .NET Framework 4.6.2 that is needed.
