### ISSUE TITLE
Equipment missing on Singleton

### ISSUE THREAD

**Issue by johmarjac** [Net-Slayer/Mordhau_uSDK#13]
Hi,

I am missing the Equipment in the Singleton. 

![image](https://user-images.githubusercontent.com/30114127/134824489-341801fa-6889-44c7-b53a-0281f9c5d52b.png)

**Comment by Net-Slayer** [comment]
yep we've just spotted this problem, its being added.

**Comment by Net-Slayer** [comment]
fixed for 1.4.1 patch going out in the hour
