### ISSUE TITLE
BP_TestCharacter , BP_PlayerTutorialCharacter, broken nodes inside blueprint. 

### ISSUE THREAD

**Issue by SoomRK** [Net-Slayer/Mordhau_uSDK#6]
Line 11937: UATHelper: Cooking (Windows):   LogInit: Display: LogBlueprint: Error: [Compiler BP_TestCharacter] The property associated with  Movement Restriction Override Duration with Rush Perk  could not be found in '/Game/Mordhau/Maps/TestMap/BP_TestCharacter.BP_TestCharacter_C' from Source: /Game/Mordhau/Maps/TestMap/BP_TestCharacter.BP_TestCharacter
	Line 11938: UATHelper: Cooking (Windows):   LogInit: Display: LogBlueprint: Error: [Compiler BP_TestCharacter] The property associated with  Movement Boost Duration with Rush Perk  could not be found in '/Game/Mordhau/Maps/TestMap/BP_TestCharacter.BP_TestCharacter_C' from Source: /Game/Mordhau/Maps/TestMap/BP_TestCharacter.BP_TestCharacter
	Line 11940: UATHelper: Cooking (Windows):   LogInit: Display: LogBlueprint: Error: [Compiler BP_PlayerTutorialCharacter] MordhauCharacter.InteractionTarget is not blueprint writable.  Set InteractionTarget from Source: /Game/Mordhau/Blueprints/GameModes/Tutorial/Characters/BP_PlayerTutorialCharacter.BP_PlayerTutorialCharacter

**Comment by Net-Slayer** [comment]
Alright so I will be copying this old map from 1.2 and updating it for 1.3.1 perk modifications are within the perk system component of AdvancedCharacter Class

**Comment by Net-Slayer** [comment]
Resolved for 1.3.1
