### ISSUE TITLE
"Banned Equipment" and "BannedPerks" variable is missing from Game-State

### ISSUE THREAD

**Issue by SoomRK** [Net-Slayer/Mordhau_uSDK#7]
"Banned Equipment" and "BannedPerks" variable is missing from Game-State, appears to be no other way to restrict equipment. 

UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MordhauGameState|General")
  TSet<TSubclassOf<AMordhauEquipment>> BannedEquipment;

UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "MordhauGameState|General")
  TSet<EPerk> BannedPerks;

**Comment by Net-Slayer** [comment]
Fixed for 1.3.1
