### ISSUE TITLE
EconomyPlayerController, EconomyPlayerState, affecting child of skrimish gamemode from compiling.

### ISSUE THREAD

**Issue by SoomRK** [Net-Slayer/Mordhau_uSDK#9]
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  <Unnamed>  no longer exists on node  Hide . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Target  no longer exists on node  Hide . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] Could not find a function named "Hide" in 'BP_EconomyPlayerController'.
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Shop Menu  no longer exists on node  Get . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Shop Menu  no longer exists on node  Get . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] Spawn node  Create Widget  must have a class specified. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Shop Menu  no longer exists on node  Get . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  <Unnamed>  no longer exists on node  Show . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Target  no longer exists on node  Show . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerController] Could not find a function named "Show" in 'BP_EconomyPlayerController'.
PackagingResults: Error: [Compiler BP_EconomyPlayerController] In use pin  Shop Menu  no longer exists on node  Set . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerController.BP_EconomyPlayerController
PackagingResults: Error: [Compiler BP_EconomyPlayerState] In use pin  Shop Menu  no longer exists on node  Get . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerState.BP_EconomyPlayerState
PackagingResults: Error: [Compiler BP_EconomyPlayerState] In use pin  <Unnamed>  no longer exists on node  Refresh . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerState.BP_EconomyPlayerState
PackagingResults: Error: [Compiler BP_EconomyPlayerState] In use pin  Target  no longer exists on node  Refresh . Please refresh node or break links to remove pin. from Source: /Game/Mordhau/Blueprints/GameModes/BP_EconomyPlayerState.BP_EconomyPlayerState
PackagingResults: Error: [Compiler BP_EconomyPlayerState] Could not find a function named "Refresh" in 'BP_EconomyPlayerState'.

**Comment by Net-Slayer** [comment]
You can simply remove the offending nodes.
As economy mode isn't really in game yet, this should have no side effects.
Investigating!

**Comment by Net-Slayer** [comment]
Resolved for 1.3.1
